# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

"""Wrap an ASSERT target with the generated ACS policy for a guarded re-run.

After generating and validating a policy, the same agent target can be re-run
through ASSERT with ACS enforcement in front of it. :func:`guard_target` returns
an async callable that routes the target's input and output through the ACS
``input`` and ``output`` intervention points, but only for the points the
effective policy actually defines. The stateless runtime fails closed with a
reserved ``runtime_error:intervention_point_unknown`` verdict on a point the
policy does not declare; the guard uses the runtime itself as the source of
truth (so it honors ``extends``-inherited points), skipping enforcement only for
that specific unknown-point error and letting every other verdict, including
other runtime errors, fail closed. A ``deny`` verdict raises
``AgentControlBlocked``; an ``escalate`` is routed to the optional approval
resolver.

Requires the optional ``agent-control-specification`` SDK
(``pip install "assert-ai[acs]"``).
"""

from __future__ import annotations

import inspect
from pathlib import Path
from typing import TYPE_CHECKING, Any, Awaitable, Callable, Mapping

import yaml

try:
    from agent_control_specification import (
        AgentControl,
        EnforcementMode,
        InterventionPoint,
    )
except ModuleNotFoundError as exc:  # pragma: no cover - exercised only without the extra
    if exc.name == "agent_control_specification":
        raise ModuleNotFoundError(
            "The ACS runtime guard requires the 'agent-control-specification' SDK. "
            'Install the ACS extra with: pip install "assert-ai[acs]"',
            name=exc.name,
        ) from exc
    raise

if TYPE_CHECKING:  # pragma: no cover - typing only
    from agent_control_specification import ApprovalResolver

# Reserved reason the stateless runtime returns (fail-closed deny) when a policy
# input targets an intervention point the effective manifest does not declare.
# Source: policy-engine core/src/error.rs (InterventionPointUnknown). Because the
# runtime resolves the full ``extends`` chain before deciding this, detecting it
# is more correct than parsing a single manifest file's top-level points.
_UNKNOWN_POINT_REASON = "runtime_error:intervention_point_unknown"


def build_agent_control(
    manifest_path: str | Path,
    *,
    approval_resolver: "ApprovalResolver | None" = None,
    perf_telemetry: int = 0,
) -> "AgentControl":
    """Build an ``AgentControl`` backed by the policy at ``manifest_path``.

    Uses the bundled OPA policy dispatcher and annotator dispatcher, so Rego
    policies generated by :func:`~assert_ai.integrations.acs.generate.generate_policy`
    integrate without extra wiring.
    """
    resolved = Path(manifest_path).expanduser()
    if not resolved.is_file():
        raise FileNotFoundError(f"ACS manifest not found: {resolved}")
    return AgentControl.from_path(
        str(resolved),
        approval_resolver=approval_resolver,
        perf_telemetry=perf_telemetry,
    )


def manifest_intervention_points(manifest_path: str | Path) -> tuple[str, ...]:
    """Return the intervention-point names declared at a manifest's top level.

    This reads only the named file and does NOT resolve ``extends``; the
    effective policy may declare additional points inherited from a base
    manifest. It is an introspection helper only. Enforcement decisions in
    :func:`guard_target` (and validation) instead use the runtime as the source
    of truth so they honor the full ``extends`` chain.
    """
    resolved = Path(manifest_path).expanduser()
    if not resolved.is_file():
        raise FileNotFoundError(f"ACS manifest not found: {resolved}")
    manifest = yaml.safe_load(resolved.read_text(encoding="utf-8")) or {}
    points = manifest.get("intervention_points")
    if not isinstance(points, dict):
        return ()
    return tuple(str(name) for name in points)


def guard_target(
    target: Callable[..., Any],
    manifest_path: str | Path,
    *,
    snapshot: Mapping[str, Any] | None = None,
    mode: str = "enforce",
    approval_resolver: "ApprovalResolver | None" = None,
    perf_telemetry: int = 0,
) -> Callable[..., Awaitable[Any]]:
    """Return an async, policy-guarded version of an ASSERT callable target.

    ``target`` is the agent entry callable (sync or async) that maps an input
    value to an output value. The returned callable enforces the ACS ``input``
    point on the argument and the ``output`` point on the result, skipping only
    the points the effective policy does not declare (detected at runtime via the
    reserved unknown-point verdict, which honors ``extends``-inherited points).
    Pass ambient per-call snapshot fields with the reserved
    ``agent_control_snapshot={...}`` keyword on the returned callable; they are
    merged over ``snapshot``.

    ``mode`` is ``"enforce"`` (block on deny) or ``"evaluate_only"`` (observe
    without blocking).
    """
    control = build_agent_control(
        manifest_path,
        approval_resolver=approval_resolver,
        perf_telemetry=perf_telemetry,
    )
    enforcement_mode = EnforcementMode(mode)
    default_snapshot = dict(snapshot or {})

    async def _enforce(point: Any, snapshot: dict[str, Any], value: Any) -> Any:
        result = await control.evaluate_intervention_point(point, snapshot, enforcement_mode)
        if _is_undeclared_point(result):
            # The effective policy does not declare this point, so there is
            # nothing to enforce; do not fail closed on the unknown-point error.
            return value
        await control.enforce(
            point, result, enforcement_mode, approval_resolver=approval_resolver
        )
        return _transformed_or(result, value, enforcement_mode)

    async def guarded(
        input_value: Any,
        *,
        agent_control_snapshot: Mapping[str, Any] | None = None,
    ) -> Any:
        ambient = {**default_snapshot, **dict(agent_control_snapshot or {})}

        effective_input = await _enforce(
            InterventionPoint.INPUT, {**ambient, "input": input_value}, input_value
        )
        output = await _maybe_await(target(effective_input))
        return await _enforce(
            InterventionPoint.OUTPUT,
            {**ambient, "input": effective_input, "output": output},
            output,
        )

    return guarded


def _is_undeclared_point(result: Any) -> bool:
    """True when the verdict is the reserved unknown-intervention-point error."""
    reason = result.verdict.reason
    return isinstance(reason, str) and reason == _UNKNOWN_POINT_REASON


async def _maybe_await(value: Any) -> Any:
    if inspect.isawaitable(value):
        return await value
    return value


def _transformed_or(result: Any, fallback: Any, mode: Any) -> Any:
    """Return the policy-transformed target only in enforce mode, else the original.

    Mirrors the SDK's ``_orchestration._transformed_or`` gate: a transform mutates
    the action only under enforcement, and per AGT only ``Decision.TRANSFORM``
    (``applies_transform``) may carry a transformed target. The applied flag and a
    non-null ``transformed_policy_target`` are both honored, matching the SDK (the
    runtime sets the flag for transforms, but the SDK contract also accepts a
    non-null target on its own). In ``evaluate_only`` (shadow) mode the target path
    is never mutated. guard_target only enforces top-level ``input``/``output``
    targets, so the SDK's nested-path splice is an identity here and is not mirrored.
    """
    if mode != EnforcementMode.ENFORCE:
        return fallback
    decision = getattr(result, "verdict", None)
    decision = getattr(decision, "decision", None)
    applies_transform = getattr(decision, "applies_transform", None)
    if applies_transform is False:
        return fallback
    if (
        getattr(result, "transformed_policy_target_applied", False)
        or getattr(result, "transformed_policy_target", None) is not None
    ):
        return result.transformed_policy_target
    return fallback


__all__ = ["build_agent_control", "guard_target", "manifest_intervention_points"]
