# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

import json
import unittest
from pathlib import Path
from tempfile import TemporaryDirectory
from unittest.mock import patch

from assert_eval.config import ConfigError, load_runtime_context
from assert_eval.runner import run_pipeline
from assert_eval.stages import STAGES


class RuntimeContextTest(unittest.TestCase):
    def test_load_runtime_context_supports_target_strings(self) -> None:
        context = load_runtime_context(
            {
                "suite": "suite-a",
                "run": "run-a",
                "behavior": {"name": "harmful_medical_advice"},
                "pipeline": {
                    "test_set": {"prompt": {"model": {"name": "azure/gpt-5.4"}}},
                    "inference": {"target": {"model": {"name": "azure/gpt-5.4"}}},
                    "judge": {"model": {"name": "azure/gpt-5.4"}},
                },
            },
            Path("examples/prompt_agents/health_assistant.yaml"),
            stage_modules=STAGES,
        )

        self.assertEqual(context["target"].model.name, "azure/gpt-5.4")
        self.assertEqual(context["run_id"], "run-a")

    def test_load_runtime_context_rejects_missing_inference_target(self) -> None:
        with self.assertRaisesRegex(ConfigError, "pipeline.inference.target is required"):
            load_runtime_context(
                {
                    "suite": "suite-a",
                    "behavior": {"name": "harmful_medical_advice"},
                    "pipeline": {
                        "inference": {"test_set_path": "test_set.jsonl"},
                        "judge": {"model": {"name": "azure/gpt-5.4"}},
                    },
                },
                Path("examples/prompt_agents/health_assistant.yaml"),
                stage_modules=STAGES,
            )

    def test_load_runtime_context_allows_disabled_stage_family(self) -> None:
        with TemporaryDirectory() as tmp_dir:
            cfg_path = Path(tmp_dir) / "config.yaml"
            context = load_runtime_context(
                {
                    "suite": "suite-a",
                    "behavior": {"name": "harmful_medical_advice"},
                    "pipeline": {
                        "systematize": {"enabled": False, "model": {"name": "azure/gpt-5.4"}},
                        "test_set": {"enabled": False, "prompt": {"model": {"name": "azure/gpt-5.4"}}},
                    },
                },
                cfg_path,
                stage_modules=STAGES,
            )

            self.assertEqual(
                [stage_name for stage_name, _ in context["stages"]],
                ["systematize", "test_set"],
            )

    def test_load_runtime_context_allows_disabled_inference_without_target(self) -> None:
        context = load_runtime_context(
            {
                "suite": "suite-a",
                "pipeline": {
                    "inference": {"enabled": False, "test_set_path": "test_set.jsonl"},
                },
            },
            Path("examples/prompt_agents/health_assistant.yaml"),
            stage_modules=STAGES,
        )

        self.assertIsNone(context["target"])
        self.assertIsNone(context["evaluation"])
        self.assertIsNone(context["run_id"])

    def test_load_runtime_context_allows_disabled_judge_without_judge_config(self) -> None:
        context = load_runtime_context(
            {
                "suite": "suite-a",
                "pipeline": {
                    "judge": {"enabled": False, "inference_set_path": "inference_set.jsonl"},
                },
            },
            Path("examples/prompt_agents/health_assistant.yaml"),
            stage_modules=STAGES,
        )

        self.assertIsNone(context["evaluation"])
        self.assertIsNone(context["run_id"])

class IdentifierValidationTest(unittest.TestCase):
    """Tests for _validate_identifier and path confinement in config.py."""

    _BASE_CONFIG = {
        "behavior": {"name": "harmful_medical_advice"},
        "pipeline": {
            "inference": {"target": {"model": {"name": "azure/gpt-5.4"}}},
            "judge": {"model": {"name": "azure/gpt-5.4"}},
        },
    }

    def _load(self, **overrides):
        raw = {**self._BASE_CONFIG, **overrides}
        return load_runtime_context(
            raw,
            Path("examples/prompt_agents/health_assistant.yaml"),
            stage_modules=STAGES,
        )

    def test_valid_suite_and_run_ids(self) -> None:
        ctx = self._load(suite="my-suite.v1", run="run_2026")
        self.assertEqual(ctx["suite_id"], "my-suite.v1")
        self.assertEqual(ctx["run_id"], "run_2026")

    def test_autogenerated_suite_id_passes(self) -> None:
        ctx = self._load()
        self.assertTrue(ctx["suite_id"].startswith("eval-"))

    def test_rejects_suite_id_with_path_traversal(self) -> None:
        with self.assertRaises(ConfigError):
            self._load(suite="../escape")

    def test_rejects_suite_id_with_slash(self) -> None:
        with self.assertRaises(ConfigError):
            self._load(suite="a/b")

    def test_rejects_absolute_suite_id(self) -> None:
        with self.assertRaises(ConfigError):
            self._load(suite="/etc/passwd")

    def test_empty_suite_id_falls_back_to_autogenerated(self) -> None:
        ctx = self._load(suite="")
        self.assertTrue(ctx["suite_id"].startswith("eval-"))

    def test_rejects_old_suite_and_run_keys(self) -> None:
        with self.assertRaisesRegex(ValueError, "unsupported field\\(s\\): run_id, suite_id"):
            load_runtime_context(
                {
                    "suite_id": "suite-a",
                    "run_id": "run-a",
                    "behavior": {"name": "harmful_medical_advice"},
                    "pipeline": {
                        "inference": {"target": {"model": {"name": "azure/gpt-5.4"}}},
                        "judge": {"model": {"name": "azure/gpt-5.4"}},
                    },
                },
                Path("examples/prompt_agents/health_assistant.yaml"),
                stage_modules=STAGES,
            )

    def test_rejects_run_id_with_traversal(self) -> None:
        with self.assertRaises(ConfigError):
            self._load(suite="suite-a", run="../../etc")

    def test_rejects_overlong_suite_id(self) -> None:
        with self.assertRaises(ConfigError):
            self._load(suite="a" * 256)

    def test_rejects_suite_id_starting_with_dot(self) -> None:
        with self.assertRaises(ConfigError):
            self._load(suite=".hidden")

    def test_rejects_concept_with_traversal(self) -> None:
        with self.assertRaises(ConfigError):
            self._load(suite="suite-a", behavior={"name": "../../../etc/passwd"})


class RunnerManifestTest(unittest.TestCase):
    def test_run_pipeline_writes_minimal_manifest(self) -> None:
        with TemporaryDirectory() as tmp_dir:
            root = Path(tmp_dir)
            cfg_path = root / "config.yaml"
            suite_root = root / "results" / "suite-a"
            suite_root.mkdir(parents=True)
            inference_set_path = suite_root / "inference_set.jsonl"
            inference_set_path.write_text(
                '{"type":"prompt","test_case_id":"test-case-1"}\n',
                encoding="utf-8",
            )
            (suite_root / "taxonomy.json").write_text("{}", encoding="utf-8")
            cfg_path.write_text(
                "\n".join(
                    [
                        "suite: suite-a",
                        "run: run-a",
                        f"results_dir: {root / 'results'}",
                        "behavior:",
                        "  name: harmful_medical_advice",
                        "pipeline:",
                        "  judge:",
                        "    model:",
                        "      name: azure/gpt-5.4",
                        f"    inference_set_path: {inference_set_path}",
                    ]
                ),
                encoding="utf-8",
            )

            async def fake_run_judge(**_: object) -> dict[str, str]:
                run_root = root / "results" / "suite-a" / "run-a"
                run_root.mkdir(parents=True, exist_ok=True)
                scores = run_root / "scores.jsonl"
                scores.write_text("", encoding="utf-8")
                return {
                    "scores_path": str(scores),
                }

            with patch("assert_eval.stages.judge.run_judge", new=fake_run_judge):
                rc = run_pipeline(config=str(cfg_path))

            self.assertEqual(rc, 0)
            manifest = json.loads(
                (root / "results" / "suite-a" / "run-a" / "manifest.json").read_text(encoding="utf-8")
            )
            suite_meta = json.loads(
                (root / "results" / "suite-a" / "suite.json").read_text(encoding="utf-8")
            )
            manifest_keys = set(manifest.keys())
            self.assertGreaterEqual(
                manifest_keys,
                {"ended_at", "stages", "started_at", "status"},
            )
            self.assertEqual(manifest["stages"]["judge"], "completed")
            self.assertEqual(manifest["status"], "completed")
            self.assertIsInstance(manifest["started_at"], str)
            self.assertIn("T", manifest["started_at"])
            self.assertIsInstance(manifest["ended_at"], str)
            self.assertIn("T", manifest["ended_at"])
            self.assertEqual(sorted(suite_meta.keys()), ["created_at"])
            self.assertIn("T", suite_meta["created_at"])
            saved_config = root / "results" / "suite-a" / "run-a" / "config.yaml"
            self.assertTrue(saved_config.exists())
            self.assertEqual(saved_config.read_text(encoding="utf-8"), cfg_path.read_text(encoding="utf-8"))

    def test_run_pipeline_records_pid_host_and_heartbeat(self) -> None:
        """Manifest carries pid/host/heartbeat_at so the viewer can detect abandoned runs."""
        with TemporaryDirectory() as tmp_dir:
            root = Path(tmp_dir)
            cfg_path = root / "config.yaml"
            suite_root = root / "results" / "suite-a"
            suite_root.mkdir(parents=True)
            inference_set_path = suite_root / "inference_set.jsonl"
            inference_set_path.write_text(
                '{"type":"prompt","test_case_id":"test-case-1"}\n', encoding="utf-8"
            )
            (suite_root / "taxonomy.json").write_text("{}", encoding="utf-8")
            cfg_path.write_text(
                "\n".join(
                    [
                        "suite: suite-a",
                        "run: run-a",
                        f"results_dir: {root / 'results'}",
                        "behavior:",
                        "  name: harmful_medical_advice",
                        "pipeline:",
                        "  judge:",
                        "    model:",
                        "      name: azure/gpt-5.4",
                        f"    inference_set_path: {inference_set_path}",
                    ]
                ),
                encoding="utf-8",
            )

            async def fake_run_judge(**_: object) -> dict[str, str]:
                run_root = root / "results" / "suite-a" / "run-a"
                run_root.mkdir(parents=True, exist_ok=True)
                scores = run_root / "scores.jsonl"
                scores.write_text("", encoding="utf-8")
                return {"scores_path": str(scores)}

            with patch("assert_eval.stages.judge.run_judge", new=fake_run_judge):
                rc = run_pipeline(config=str(cfg_path))

            self.assertEqual(rc, 0)
            manifest = json.loads(
                (root / "results" / "suite-a" / "run-a" / "manifest.json").read_text(encoding="utf-8")
            )
            self.assertIn("pid", manifest)
            self.assertIsInstance(manifest["pid"], int)
            self.assertGreater(manifest["pid"], 0)
            self.assertIn("host", manifest)
            self.assertIsInstance(manifest["host"], str)
            self.assertGreater(len(manifest["host"]), 0)
            self.assertIn("heartbeat_at", manifest)
            self.assertIsInstance(manifest["heartbeat_at"], str)
            self.assertIn("T", manifest["heartbeat_at"])


if __name__ == "__main__":
    unittest.main()
